---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gateway-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: gateway-dev
  chart:
    git: git@github.com:wynnel/puma-gitops
    path: charts/gateway
    ref: master
  valuesFrom:
  - secretKeyRef:
      name: gateway-secret-values
  - secretKeyRef:
      name: gateway-license-value
      key: license.yaml
  values:
    replicaCount: 2
    image:
      imageName: docker.sandbox2.apimgcp.com/repository/docker-hosted/gateway
      tag: latest 
    imageCredentials:
      name: "docker.sandbox2.apimgcp.com"
      registry: "docker.sandbox2.apimgcp.com"
      username: "admin"
    hazelcast:
      enabled: false
    influxdb:
      host: "apim-service-metrics-runtime-influxdb.default"
    service:  
      ports:
        - name: http
          internal: 8080
          external: 80
        - name: https
          internal: 8443
          external: 443
    gateway:
      license:
        accept: "true"




