apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secret-values
  namespace: dev
spec:
  encryptedData:
    values.yaml: AgCNj6WG05t19jr8fFQu6mfVV6Qs9pRHzXbIidjV1TW0RJODPYa83FDYwXkVE5ZuXceO8GTAwkLqSfFPQWCuDgToxR2H3uLmBhuD70xWwzR9vSRVHEVUWo2a+Rn+fhuFMHjjH53rlJl/c6IjgJYEFAFPIHU1n27jGOj0owGhBz2MzyBZ1YQa2vpnxu3w5f5q/P/Xgym55xbkAXMyhuP6JMy/FX7+mKIaH2MT/5ztLMpPabYG1FYtpRVHA2l9c7Kc6WkflcXL3071GfvhcoKobU+ihdlOcsRj33g+jwDwmAZpJ8F7SVn5U8WpnJ2lwHWtB0axbNQ8e9k9v5sogoyni6ffRIvPSxewVhzBOxJanhPJ+hYXzXzrwDCYdIj71rMvYk3ljJjtig/8y7bfQ2zge581Y2gYAsdq+mxV/7TVO/GJ0yYR8IL1HXPiRpsm9nQuEPhENqmnVtDrREwx3VpfLBOWGYu6wCE6CD2JE32UKmIGYGpkrdP4JhyAtI3nTVNeOFXPgdDn0rNHPEQx6eeqi35k6mrtBgb/HhAHW36VNuOCcdR2vLIjrdNLPpK+81nwHqkfPeqE+w0yvZgxMHjXYPNYl6wSC4pajBfOX6reP7bnMYs+sZyysK+ggFxSeN/mJsBFvJ7y5sgrTvLKPg7P/2rweL/3ZOySfevfanm7kS9PxwwDigv+YNpKWbWNE8WYFFRflFPPXs0qSlYgPuEpLE7mNlBpl4NbC/3oTL9sBI/QrxEPSLw3TYW7a3I71nePypLsonwJUGEypXTNd0SZ90gwkTsHNIvWBFZf3if3/sR9K0EdFR6DapqcT1TwjjbgI2y38+BOyjFd1//xrtUcS90AhJ2upwaH658gYFZ8lXKitc6sKdt97U5pTXCacuxvhCIghKxiurC2IlTxPeOlP0vmzwmPwIuEFZfJGLxCBPFemQnIquUgA4IEkWe52wkYWwU37ZVl5UXbGTZThttGG10/3pWyO1y3JeaEk9fuoux58eLtJAhDG8HR

